travis:
  secure:
    BINSTAR_TOKEN: FqM1mh6fx3RwmUEGIrnX3IvFmEA1xdORx3t7/9Bu3hBNMGC4caXuZdhNETgHnc5FCTg1EnozmgwgZ/eZP4b+s+lEO545QVzRAMdtuK5vSsAI4gwQ6TgWLItUjWV2LsvQgDludo0cxcr5whqbugRoAfOjwNLVjxoll3dVjoihMVHiSfGjowgqOW6D0AHdSB2ehac/228w0sZYl24Uvz3Az26IkmgWFjSHKob+j8DH9lq8piokczOklJUKRwH8EB7TtYE/w7EHEnyx0CPfCk+cjY3WjPBz9W0w777NjYiCCrv83gJtfKcZCK4sc51ZVcuDdbz40V472xJToELcCzrneztOvhxdvU+gWm2fRapJ2yiX1ZiI5nkHY6N8hpUZ6yIJzJ1ws0UDQYd67bs5Wgup6z8nqmUq6eiGa5H8A0GBYpIPNzHu3UJaysBgy3ohgssuubmjeL70IYjqmrm7J5jl8oTGZRr89CG9Uk03fsBKf7aTjw6gBu9HOcU1GxUB3rowNX+4MU6LPYnrxM6ztMqlLX0Dcv6T5JYFBlHulJH3WXorz5UsfXb38kBCO9g2yqayJ7R67xyEpq429QCY9O6VpyBVgeirihyolJxnLRWMlmFgniMuo9YKaY/YEqP9sv2vDJE/3pv0oot+1pIOB8VTkEl0+7AnmEQKOoy7f++2WjU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
