travis:
  secure:
    BINSTAR_TOKEN: bduWanW/onPJy5PNh3JTW1BcsKr9BTK5TQ99xdpmWkZ7o3F/dT+Js58Vt+TzwMFGMFnqCgME4cM6cPPiGkNUXhoSQOHU+vbg3v9TiV4YV29U44V0TyfdBdHzC/W56l7Ke18mKTI9J3p/q4XgasG9Ltb4WlZM1B8LCAQPYcQ3iL9N8WyX908yIz4gCWglKTLsIM4kSxSRDWD9hwPtqsYdQ40NyxJu5qErk96FIICL2guRVhGeUixDtycJglaLGuyVkTM/qYuRN4Xd38xwTxp0E9ovNUDSmpCgEyIZPyCWjExR2NwO92YSGauyFvXp93KEGgIfD932MAl8bZynMq4VjaDAXdqVMVkI+TKR2Kd5fyKbtUB+yBmhF+nav3ZcCMufYYxhjUpNfxABc9wSheMHf1w9o6v4WhWwgxI1iH+Bl/fVQAOwlMPHDmoB/nd4lEg8zfcahOb6Qf4P9hkVfdrb66jwpbBrt105souERy1tnlr2LKnMyF296wI2eYO0K52TYs9ZDUBBDWhRDO2bIpIhvS1mUQHb/TxX0Xl1T3mZb0oSwwBRNf4s/iTfIAVs36XZL3kcGLAP0aMmDCO5O3/AWRkFfj7bOabfQxiNq6G9eu4n9IwwKObtnB8wrIuAyG2BggHGiE7j+8d9skwcRc7acTJk/aW1szOEGHwh2DRryp0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
